config/routes.rb
Rails.application.routes.draw do
  get 'likes/index'
  get 'comments/index'
  devise_for :views
  # Redirests signing out users back to sign-in
get "users", to: "devise/sessions#new"
  devise_for :users
  get 'tweets/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
resources :tweets do
  member do
    post :retweet
  end
  resources :likes ,module: :tweets, only: :create 

  resources :comments do
    resources :likes ,module: :comments, only: :create 
   
  end
end
  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :tweet
    belongs_to :user
    has_many :likes , as: :likable


end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likable, polymorphic: true
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    belongs_to :tweet,optional: true
    has_many :likes , as: :likable
    validates :tweeet,presence:true
  

 

        def tweet_type
            if tweet_id? && tweeet?
              "quote-tweet"
            elsif tweet_id?
              "retweet"
            else
              "tweets"
            end
        end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
  has_many :comments
  has_one :like,as: :likable 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
        devise_parameter_sanitizer.permit(:sign_in) do |user_params|
          user_params.permit(:username, :email)
        end
      end

      

end

app/controllers/comments/likes_controller.rb
class Comments::LikesController<LikesController
    before_action :set_likable


    private
    def set_likable
        @likable= Comment.find(params[:comment_id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment ,only: %i[edit show update destroy]
  def index
    @comments=Comment.all
  end

  def like


    @tweet=Tweet.find(params[:tweet_id])
    @comment=@tweet.comments.find(params[:id])
    @like=Like.create(tweet_id: @tweet.id,user_id:current_user.id)
    respond_to do |format|
  
   if @like.save
    format.turbo_stream 
  
   end
  end
  end
  def show
    
  end
def new
  @comment=Comment.new
  @tweet=Tweet.find(params[:tweet_id])
end
def create

  @tweet=Tweet.find(params[:tweet_id])
  @comment=@tweet.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.turbo_stream
        format.html { redirect_to tweets_path ,notice: 'Comment was successfully created.'}
        format.json{render :show ,status: :ok,location:@comment}
      else
        format.html { render :new ,status: :unprocessable_entity}
        format.json {render json:@comment.errors,status: :unprocessable_entity}

    end
  end

end

def destroy
  @comment.destroy
  redirect_to root_path, notice: 'Comment was deleted'
end
  def comment_params
    params.require(:comment).permit(:body,:tweet_id,:user_id)
  end
  def find_comment
    @comment=Comment.find(params[:id])
    @tweet=Tweet.find(params[:tweet_id])


  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController



def new
  @like=@likable.likes.new
end
def create
  @like=@likable.likes.create(user_id:current_user.id)
  respond_to do |format|
  if @like.save
    format.turbo_stream
  end 
end

end
def like_params
  params.require(:like).permit(:likable_type,:likeable_id,:user_id)
end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
  end

app/controllers/tweets/likes_controller.rb
class Tweets::LikesController<LikesController
    before_action :set_likable


    private
    def set_likable

        @likable=Tweet.find(params[:tweet_id])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :find_tweet ,only: %i[show edit destroy update] 
  before_action :authenticate_user!,except:[:show,:index]
  def index  
    @tweet=Tweet.new
    @likes=Like.all


      @tweets = Tweet.all.order(created_at: :desc)
      @notweet="Nothing to show Here"
    if current_user
    @user_tweets=current_user.tweets.count
    end
end 
def show
  @tweet = Tweet.find(params[:id])
  @comment = Comment.new
  @comments = @tweet.comments.order(created_at: :desc)
end

  

def destroy
  @tweet.destroy
  
  redirect_to tweets_path
end
def new
  @tweet=current_user.tweets.build
end
def retweet
  @tweet=Tweet.find(params[:id])
  retweet=current_user.tweets.new(tweet_id: @tweet.id)
  respond_to do |format|
    if retweet.save
      format.turbo_stream
    else
      format.html {redirect_back fallback_location: @tweet,notice:"Retweeted"}
    end
  end
end
def like

  @tweet=Tweet.find(params[:id])
  @like=Like.create(tweet_id: @tweet.id,user_id:current_user.id)
  respond_to do |format|

 if @like.save
  format.turbo_stream 

 end
end
end

def create
  @tweet=current_user.tweets.build(tweett_params)

    respond_to do |format|
      if @tweet.save
        format.turbo_stream 
        format.html {redirect_to tweets_path,notice:"tweeted"}
        format.json{render :show,status: :ok,location:@tweet}
      else
        format.html {render :new,status: :unprocessable_entity}
        format.json{render json: @tweet.errors,status: :unprocessable_entity}
      end    
  end

end

def edit

end
def update
  @tweet.update(tweett_params)
  respond_to do |format|
    if @tweet.update(tweett_params)
      format.html{redirect_to tweets_path,notice:"Updated well"}
      format.json{render :show ,status: :ok,location:@tweet}
    else
      format.html{render :edit,status: :unprocessable_entity}
      format.json {render json:@tweet.errors,status: :unprocessable_entity}
    end
  end
end

def tweett_params
  params.require(:tweet).permit(:tweeet,:user_id,:tweet_id)
end
def find_tweet
  @tweet=Tweet.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/comments/_comment.html.erb
<p> <%=  comment.body%></p>
<nav class="level">
<div class="level-left is-mobile">

<%=  link_to tweet_comments_path(@tweet),class:"level-item"  do %>
<i class="fa fa-commenting" aria-hidden="true">
<div id="<%=dom_id @tweet%>_comment">
<%= render partial: "tweets/countComments" ,locals:{tweet:@tweet}%>
</div>
</i><% end %>
<%=  link_to root_path  ,class:"level-item"  do %>
<i class="fa fa-retweet" aria-hidden="true">
<%= render partial: "tweets/countComments" ,locals:{tweet:@tweet}%>

</i><%end%>


<%=  button_to  tweet_comment_likes_path(@tweet,comment) , method:  :post ,class:"level-item"  do %>
<i class="fa fa-heart-o" aria-hidden="true" id="likes">
<div id="<%=dom_id comment%>_like">
<%= render partial:  "comments/likes", locals: { comment: comment }%>
</div>

</i>
<%end%>



<%=  link_to root_path  ,class:"level-item"  do %>
<i class="fa fa-bar-chart" aria-hidden="true"></i>
<%= render partial: "tweets/countComments" ,locals:{tweet:@tweet}%>

</i><%end%>


<%= link_to  tweet_comment_path(@tweet,comment), method:  :delete,data:{confirm:"Are you sure?"} ,class:"level-item ",id:"del"  do %>
<i class="fa fa-trash-o  "  id="del_btn" aria-hidden="true"></i> <%end%>
</div>
</nav>

app/views/comments/_comments.html.erb
<h4>Tweet comments</h4>
<%comments.each do |comment|%>
<div id="<%=dom_id comment%>">


<%= render "comments/comment",  comment: comment%>

</div>
<%end%>

app/views/comments/_form.html.erb
<%= form_with model: [tweet, @comment], data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } do |form| %>


<%= form.text_field :tweet_id ,type:"hidden",value:params[:tweet_id]%>
<%= form.text_field :user_id ,type:"hidden",value:current_user.id%>


<%= form.text_field :body%>

<%= form.submit "Reply"%>
<%end%>

app/views/comments/_likes.html.erb
<%= comment.likes.count%>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.after "#{dom_id(@tweet)}_comments" do %>
  <%= render "comment", comment: @comment %>
<% end %>

<%= turbo_stream.update "#{dom_id(@tweet)}_comment" do %>
<%= render partial: "tweets/countComments", locals: {tweet:@tweet}  %>
<% end %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<%= render "form"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if flash[:notice]%>
  <div class="notification is-primary global-notification py-0 my-0">
   <p class="notice my-0"><%= notice %></p>
   </div>
   <% end %>
     <% if flash[:alert]%>
  <div class="notification is-danger global-notification py-0">
   <p class="alert  my-0"><%= alert %></p>
   </div>
   <% end %>




 <nav class="navbar navbar-expand-md navbar-primary bg-info py-0" >
  <div class="container-fluid  py-0 " id="nav_collapse">
  <%= link_to "Twitter", root_path, class:"navbar-brand"%>
    <div>
    <button class="navbar-toggler p-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    </div>
     <div class="navbar-collapse collapse  "  id="navbarNav" >

      <ul class="navbar-nav ">
      
        <li class="nav-item">
              <%= link_to "Tweet",new_tweet_path,class:"button is-info is-small is-inverted mr-1"%>

        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to current_user.username, edit_user_registration_path,class:"mr-2"%>

        </li>
         <li class="nav-item">
              <%= link_to "Sign-out", destroy_user_session_path,method: :delete,class:""%>

        </li>
        <% else %>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path,class:"mr-2"%>

        </li>
          <li class="nav-item">
              <%= link_to "Sign-up", new_user_registration_path,class:""%>

        </li>

        <% end %>
     
      </ul>
    </div>
  </div>
</nav>



    <%= yield %>
  </body>
</html>

app/views/likes/create.turbo_stream.erb
<%= turbo_stream.update "#{dom_id(@likable)}_like" do %>
<%= render partial: "comments/likes", locals: {comment:@likable} %>
<% end %>

app/views/tweets/_countComments.html.erb
<%=tweet.comments.count%>

app/views/tweets/_form.html.erb
<div class="tweets">
<%= form_with(model: tweet, id:"#{dom_id(tweet)}_form") do |form|%>
<%= form.text_area :tweeet,class:"form-control" ,placeholder:"What's happening?"%>

<div id="tweet_btn">
    <%= form.submit  %>


</div>

<%end%>
</div>

app/views/tweets/_likes.html.erb
<%= tweet.likes.count%>

app/views/tweets/_menu.html.erb
<ul class="menu_items">

<li class="menu_item is-inline "> 
<a href="<%= tweets_path%>"> 

<i class="fa fa-home" aria-hidden="true"></i><span class="ml-3  d-none d-lg-inline">Home</span>

</a>

</li>

<li class="menu_item is-inline"> 


<a href="<%= tweets_path%>"> 

<i class="fa fa-hashtag" aria-hidden="true"></i></i><span class="ml-3  d-none  d-lg-inline">Explore</span>

</a>

</li>

<li class="menu_item is-inline"> 

<a href="<%= tweets_path%>"> 

<i class="fa fa-bell" aria-hidden="true"></i></i><span class="ml-3    d-none  d-lg-inline">Notifications</span>

</a>
</li>

<li class="menu_item is-inline"> 

<a href="<%= tweets_path%>"> 

<i class="fa fa-envelope-o" aria-hidden="true"></i></i><span class="ml-3  d-none  d-lg-inline">Messages</span>

</a>
</li>

<li class="menu_item is-inline"> 
<a href="<%= tweets_path%>"> 

<i class="fa fa-user" aria-hidden="true"></i></i><span class="ml-3   d-none  d-lg-inline">Profile</span>

</a>
</li>

<li class="menu_item is-inline"> 
<a href="<%= tweets_path%>"> 

<i class="fa fa-ellipsis-h" id="ellipse" aria-hidden="true"></i><span class="ml-3  d-none   d-lg-inline">More</span></a>
</li>
</ul>

app/views/tweets/_showTweet.html.erb
<p class="level">
<div class="level-left is-mobile">

<%= link_to root_path ,class:"level-item" do%>
<i class="fa fa-arrow-left" aria-hidden="true"></i>
<%end%> 

<%= link_to "Tweet", new_tweet_path , class:"level-item"%>
</div>
</p>

      <%= render "comments/form", tweet: @tweet %>


<p class="mb-1">
 <%=tweet.tweeet%>
</p>
<nav class="level">
<div class="level-left is-mobile">
<% if user_signed_in?%>
<% if current_user.username==tweet.user.username%>




<%=  button_to  tweet_likes_path(tweet) , method:  :post ,class:"level-item"  do %>
<i class="fa fa-heart-o" aria-hidden="true" id="likes">
<div id="<%=dom_id tweet%>_like">
<%= render partial:  "tweets/likes", locals: { tweet: tweet }%>
</div>

</i>
<%end%>


<%=  link_to  tweets_path,class:"level-item"  do %>
<i class="fa fa-home" aria-hidden="true"></i><% end %>
<%=  link_to  edit_tweet_path(tweet) ,class:"level-item" do %>
<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
<%end%>


<%=  link_to  tweet_path(tweet),class:"level-item"  do %>
<i class="fa fa-commenting" aria-hidden="true">
<div id="<%=dom_id tweet%>_comment">

<%= render partial: "tweets/countComments" ,locals:{tweet:tweet}%>
</div>
</i><% end %>



<%= link_to tweet  , method:  :delete,data:{confirm:"Are you sure you want to delete this tweet"} ,class:"level-item ",id:"del"  do %>
<i class="fa fa-trash-o  "  id="del_btn" aria-hidden="true"></i> <%end%>
<% end %>
<%end%>

</div>




</nav>

app/views/tweets/_teamo.html.erb
<%= turbo_stream_from "tweet"%>
<%= turbo_frame_tag "tweet" do%>
<div class="box">
<article class="media">
<div class="media-left">
<figure class="image is-64x64">
<%= gravatar_image_tag(tweet.user.email,size:64,alt:tweet.user.username)%>
  </figure>
</div>
<div class="media-content">
<div class="content">
<strong> Andrew Carnergie</strong><br/>
<% if current_user%>
<small><%= tweet.user.username%></small> <br/>

<small><%= tweet.user.email%></small> <br/>
<%end%>



<p class="mb-1">
 <%=tweet.tweeet%>
</p>

<nav class="level">
<div class="level-left is-mobile">
<% if user_signed_in?%>
<% if current_user.username==tweet.user.username%>
<%=  link_to  tweet_path(tweet),class:"level-item"  do %>
<i class="fa fa-eye" aria-hidden="true"></i>

<% end %>
<%=  button_to  like_tweet_path(tweet) , method:  :post ,class:"level-item"  do %>
<i class="fa fa-heart-o" aria-hidden="true" id="likes">
<div id="<%= dom_id tweet %>">
<%= render partial:  "tweets/likes", locals: { tweet: tweet }%>
</div>

</i>
<%end%>


<%=  button_to  retweet_tweet_path(tweet) , method:  :post ,class:"level-item"  do %>
<i class="fa fa-retweet" aria-hidden="true"></i><%end%>

<%= link_to  tweet, method:  :delete,data:{confirm:"Are you sure you want to delete this tweet"} ,class:"level-item ",id:"del"  do %>
<i class="fa fa-trash-o  "  id="del_btn" aria-hidden="true"></i> <%end%>
<% end %>
<%end%>

</div>
</nav>
</div>
</div>

</article>
</div>
<% end %>
</div>

app/views/tweets/_tweet.html.erb
<%= turbo_stream_from "tweet"%>
<%= turbo_frame_tag "tweet" do%>
<div class="box">
<article class="media">
<div class="media-left">
<figure class="image is-64x64">
<%= gravatar_image_tag(tweet.user.email,size:64,alt:tweet.user.username)%>
  </figure>
</div>
<div class="media-content">
<div class="content">
<strong> Andrew Carnergie</strong><br/>
<small><%= tweet.user.username%></small> <br/>

<small><%= tweet.user.email%></small> <br/>



<p class="mb-1">
 <%=tweet.tweeet%>
</p>

<nav class="level">
<div class="level-left is-mobile">



<%=  link_to  tweet_path(tweet),class:"level-item"  do %>
<i class="fa fa-eye" aria-hidden="true"></i>
<%end%>

<%=  button_to  tweet_likes_path(tweet) , method:  :post ,class:"level-item"  do %>
<i class="fa fa-heart-o" aria-hidden="true" id="likes">
<div id="<%=dom_id tweet%>_like">
<%= render partial:  "tweets/likes", locals: { tweet: tweet }%>
</div>

</i>
<%end%>


<%=  button_to  retweet_tweet_path(tweet) , method:  :post ,class:"level-item"  do %>
<i class="fa fa-retweet" aria-hidden="true"></i><%end%>

<%= link_to  tweet, method:  :delete,data:{confirm:"Are you sure?"} ,class:"level-item ",id:"del"  do %>
<i class="fa fa-trash-o  "  id="del_btn" aria-hidden="true"></i> <%end%>

</div>
</nav>
</div>
</div>

</article>
</div>
<% end %>

app/views/tweets/create.turbo_stream.erb
<%= turbo_stream.after "tweets" do %>
  <%= render "tweet", tweet: @tweet %>
<% end %>

<%= turbo_stream.replace "#{dom_id(Tweet.new)}_form" do %>
<%= render partial: "tweets/form" ,locals: {tweet:Tweet.new} %>
<% end %>

app/views/tweets/destroy.turbo_stream.erb
<%= turbo_stream_from.remove (@tweet)%>

app/views/tweets/edit.html.erb
<h3>Edit <%= @tweet.id%> tweet</h3>
<%= render partial: "tweets/form", locals:{tweet:@tweet}%><%= link_to "Home", tweets_path%>

app/views/tweets/like.turbo_stream.erb
<%= turbo_stream.update "#{dom_id(@item)}_like" do %>
<%= render partial: "tweets/likes", locals: {tweet:@item}  %>
<% end %>

app/views/tweets/new.html.erb
<%= render partial: "tweets/form", locals:{tweet:Tweet.new}%>

app/views/tweets/retweet.turbo_stream.erb
<%= turbo_stream.prepend "tweets" do %>
  <%= render "tweets/retweet", tweet: @retweet %>
<% end %>

app/views/tweets/show.html.erb
<div class="container">
<h3> show tweet</h3>

<%= render partial:  "tweets/showTweet", locals: { tweet: @tweet }%>
  <%= turbo_frame_tag "#{dom_id(@tweet)}_comments" do %>

<%= render partial:  "comments/comments", locals: { comments: @comments }%>
    <% end %>


</div>